### ISSUE TITLE
DSN parser fails when the password is empty

### ISSUE THREAD

**Issue by vlukashov** [soluble-io/cache-interop#800]
Thanks for keeping the the `@soluble/dsn-parser` package in the open source! It's small and convenient to use, and it does its job pretty well.

---

When using the `parseDsn()` function from the `@soluble/dsn-parser` npm pacakge, as a developer I would expect that DSN strings with an empty password are parsed correctly into an object like `{ password: '', ... }`. This does not seem to be the case with v1.6.0:

```
> const p = require('@soluble/dsn-parser')
undefined
> p.parseDsn('mysql://alice:@localhost:3306/mydb')
{ success: false, reason: 'PARSE_ERROR', message: 'Cannot parse DSN' }
> p.parseDsn('mysql://alice@localhost:3306/mydb')
{
  success: true,
  value: { driver: 'mysql', host: 'alice@localhost', port: 3306, db: 'mydb' }
}
>
```

In the first case `parseDsn('mysql://alice:@localhost:3306/mydb')` fails with an error.
In the second case `parseDsn('mysql://alice@localhost:3306/mydb')` does not fail, but returns an incorrect host name (`alice@localhost:3306` instead of `localhost:3306`)

**Comment by belgattitude** [comment]
@vlukashov thanks for reporting. Appreciated ! https://github.com/soluble-io/cache-interop/pull/816 will fix it and I'll release very soon

**Comment by belgattitude** [comment]
Can you check with 

https://github.com/soluble-io/cache-interop/releases/tag/%40soluble%2Fdsn-parser%401.7.5

**Comment by vlukashov** [comment]
@belgattitude, thanks for releasing a new version in the fix! It seems to resolve the issue for me.
